package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.util.HashMap;

import DataObjects.AppFunctions;
import DataObjects.UserFunctions;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;
/**
 * AddAppController Contains event handlers for adding application to Database
 * @author icearik
 *
 */
public class AddAppController {
	@FXML
	private Button submitBut;
	@FXML
	private Label lblapp;
	@FXML
	private TextField txtapp;
	@FXML
	private TextField txtcom;
	@FXML
	private TextArea brief;
	@FXML
	private TextArea detailed;
	@FXML
	private Button uploadBut;
	@FXML
	private Label lblFile;
	final FileChooser fileChooser = new FileChooser();
	// Event Listener on Button[#submitBut].onAction
	@FXML
	private AppFunctions functions;
	@FXML
	/**
	 * initialize runs first. initializes the AppFunctions object
	 */
	void initialize() {
		// to do
		functions = new AppFunctions();
	}
	/**
	 * Gets the contents of all textfields and submits then into database
	 * closes the window on success
	 * @param event Click submit button
	 * @throws Exception If the insertion is not possible, exception is thrown
	 */
	@FXML
	public void submit(ActionEvent event) throws Exception {
		// TODO Autogenerated
		HashMap<String, String> map = new HashMap();
		map.put("appID", txtapp.getText());
		map.put("developer", txtcom.getText());
		map.put("imageID", lblFile.getText());
		map.put("bDesc", brief.getText());
		map.put("dDesc", detailed.getText());
		map.put("uDesc", "No updates");
		map.put("price", "0");
		map.put("version", "1");
		functions.insert(map);
		Node  source = (Node)  event.getSource(); 
		Stage stage  = (Stage) source.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#uploadBut].onAction
	/**
	 * Event Listener on Button[#uploadBut].onAction. Uploads a piocture from a give file
	 * @param event click upload button
	 */
	@FXML
	public void upload(ActionEvent event) {
		// TODO Autogenerated
		File file = fileChooser.showOpenDialog(new Stage());
		if (file != null) {
			String path = file.toString();
            lblFile.setText(path.substring(path.lastIndexOf("/") + 1));
        }
	}
}
