package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.util.HashMap;

import DataObjects.UserFunctions;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class RegisterController {
	@FXML
	private TextField txtUsername;
	@FXML
	private PasswordField txtPassword1;
	@FXML
	private PasswordField txtPassword2;
	@FXML
	private Label lblStatus;
	@FXML
	private TextField txtName;
	@FXML
	private TextField txtEmail;

	@FXML
	private UserFunctions functions;
	@FXML
	/**
	 * initialize UserFunctions object
	 */
	void initialize() {
		// to do
		functions = new UserFunctions();
	}
	/**
	 *  Event Listener on Button.onAction. Gets the information from textfields and submits it to
	 *  Database. On success closes and opens Login form
	 * @param event Sign up button pressed
	 * @throws Exception
	 */
	@FXML
	public void register(ActionEvent event) throws Exception {
		// TODO Autogenerated
		if ((txtPassword1.getText().equals(txtPassword2.getText()))) {
			HashMap<String, String> map = new HashMap();
			map.put("userID", txtUsername.getText());
			map.put("password", txtPassword1.getText());
			map.put("name", txtName.getText());
			map.put("email", txtEmail.getText());
			map.put("userStatus", "user");
			try {
				functions.insert(map);
				Stage primaryStage = new Stage();
				Parent root;
				FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Login.fxml"));
				root = (Parent) fxmlLoader.load();
				Scene scene = new Scene(root,300,300);
				scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
				primaryStage.setScene(scene);
				primaryStage.show();
				Node  source = (Node)  event.getSource(); 
			    Stage stage  = (Stage) source.getScene().getWindow();
			    stage.close();
			} catch (Exception e) {
				lblStatus.setText(e.getMessage());
			}
		} else {
			lblStatus.setText("Passwords don't match");
		}
	}
}
